@echo off
echo Killing existing Python processes...
taskkill /F /IM python.exe 2>nul
echo Starting server...
start /min python main.py
echo Waiting for server to start...
timeout /t 5 /nobreak >nul
echo Running debug script...
python debug_data_flow.py
pause